### ISSUE TITLE
Encapsulate Better

### ISSUE THREAD

**Issue by gabilan** [Bentley912/Bamazon#1]
Looking at bamazonmanager. Particularly:
https://github.com/Bentley912/Bamazon/blob/master/bamazonmanager.js#L39

Should restructure actions on "answers.choice" into separate methods. Right now the code is not written in proper, discrete units.

1. Makes the code easier to follow and refactor
2. Easier to write unit tests for individual functionality.

**Comment by Bentley912** [comment]
Thanks for looking through. We are learning about ORM and Sequelize this week. Good to know our curriculum is on track with industry standards. I will keep you posted as I learn more
