### ISSUE TITLE
SQL querying issues

### ISSUE THREAD

**Issue by gabilan** [Bentley912/Bamazon#2]
Right now all SQL queries are inline. The model and querying model are not aligned. It's not clear what the schema of the underlying data structure is. Try moving to an ORM (object-relational mapper) solution. It's easier to read and more clear about intent.

http://docs.sequelizejs.com/en/v3/

**Comment by gabilan** [comment]
Using a library like sequelize will also make it easier to implement transactions. That is, you can rollback and commit transactions. Which is paramount for an ordering system in case of failure.

**Comment by Bentley912** [comment]
Thanks Ernest for checking it out. We are learning about ORM and sequelize this week. Good to know we are aligned with industry standard. I'll keep you posted as I progress. I still have 2.5 more months to go.
